import { workbenchStyles } from "./styles.ts"
import { workbenchScript } from "./script.ts"
import { nativeBridgeScript } from "./native-bridge.ts"
/** Static shell; runtime values are inserted with textContent. */
export const workbenchPage = String.raw`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OpenGUI 手机工作台</title><style>STYLES</style></head><body>
<a class="skip" href="#main">跳到主要内容</a><header><a class="brand" href="#home">OpenGUI<small>手机任务工作台 · <span id="host"></span></small></a><nav aria-label="主要导航"><a href="#home">首页</a><a href="#devices">设备</a><a href="#tasks" id="historyToggle">任务</a></nav><a href="#settings" id="settingsToggle" class="settings">设置</a></header><div id="error" class="notice" role="alert"></div><main id="main" tabindex="-1">
<section id="homePage" class="page"><div class="eyebrow">工作台 / 首页</div><h1>你想完成什么任务？</h1><p class="muted">从一个任务开始。还没连接手机，也可以先看看。</p>
<form id="taskForm" class="composer"><label for="goal">新任务</label><textarea id="goal" required maxlength="8000" placeholder="例如：打开系统设置，找到 Android 版本。"></textarea><div class="row submit-row"><small id="setupHint">也可以在宿主会话里下达任务。</small><button id="submit" class="primary">开始任务</button></div></form>
<section class="section"><div class="head"><h2>我的设备</h2><a href="#devices">查看全部</a></div><p id="deviceSummary" class="status-line"></p><div id="homeDevices" class="grid device-grid space"></div><div class="row space"><a href="#guide">连接指南 →</a><button id="refresh" type="button">刷新手机</button></div></section>
<section class="section"><h2>试试这些任务</h2><div id="examples" class="examples"></div></section><section class="section"><div class="head"><h2>最近任务</h2><a href="#tasks">所有任务</a></div><div id="recentTasks" class="task-list history-list"></div></section></section>
<section id="devicesPage" class="page" hidden><div class="head"><div><div class="eyebrow">设备</div><h1>手机画面与状态</h1></div><a href="#guide">连接指南</a></div><p class="muted">查看手机不会改变任务分配。系统按任务自动安排手机，每个执行分支固定使用一台手机。</p><div class="row space"><button id="refreshDevices">刷新设备</button></div><div id="allDevices" class="grid device-grid space"></div></section>
<section id="devicePage" class="page" hidden><a class="back" href="#devices">← 所有设备</a><div class="head"><h1 id="deviceTitle">手机画面</h1><span id="deviceStatus" class="pill"></span></div><p class="muted">实时画面只用于查看。手机操作由任务执行，点击画面不会控制手机。</p><div class="live-device"><p id="previewEmpty" class="empty">正在准备画面…</p><iframe id="deviceViewer" title="设备实时画面" hidden></iframe></div><div class="row space"><button id="hidePreview">隐藏画面</button><button id="useDevice" class="primary">在这台手机上创建任务</button></div></section>
<section id="tasksPage" class="page" hidden><div class="head"><div><div class="eyebrow">统一任务记录</div><h1>任务</h1></div><button id="new">＋ 新任务</button></div><p class="muted">宿主和网页发起的任务都在这里，记录、结果与证据保持一致。</p><div id="filters" class="filters"><button data-filter="all" aria-pressed="true">全部</button><button data-filter="active" aria-pressed="false">进行中</button><button data-filter="done" aria-pressed="false">已结束</button></div><div id="history" class="task-list history-list"></div></section>
<section id="taskPage" class="page" hidden><a class="back" href="#tasks">← 所有任务</a><h1 id="goalView"></h1><details id="goalDetails" class="goal-details" hidden><summary>查看完整任务目标</summary><p id="fullGoal"></p></details><p id="taskMeta" class="meta"></p><div class="row task-controls"><span id="state" class="pill" aria-live="polite"></span><button id="stop" class="danger">停止任务</button><button id="reuse" hidden>用此任务创建草稿</button><button id="export">导出记录</button></div><div id="taskNotice" class="notice" hidden></div><section id="branches" class="section" hidden><h2>执行分支</h2><div id="branchCards" class="grid"></div></section><div class="detail-grid"><section class="task-screen"><div class="head"><h2>手机画面</h2><button id="toggleScreen">隐藏画面</button></div><p id="empty" class="empty">等待任务画面。</p><iframe id="viewer" title="Android 实时画面" hidden></iframe></section><section class="task-content"><h2>执行结果</h2><p id="result" aria-live="polite"></p><p id="checks" class="muted"></p><small id="usage"></small><h2>操作记录</h2><p class="source-note">记录实际动作与状态变化。</p><ol id="timeline" class="timeline" aria-label="执行步骤"></ol><section id="steering"><h2>补充指令</h2><label class="sr-only" for="instruction">补充指令</label><textarea id="instruction" maxlength="8000" placeholder="补充要求会在下一次决策时生效。"></textarea><div class="row space"><button id="steer">提交补充</button></div></section><section class="evidence"><h3>截图证据</h3><p id="noEvidence" class="no-evidence">还没有截图证据。</p><label id="evidenceLabel" for="evidenceSelect" hidden>选择记录的画面</label><select id="evidenceSelect" hidden></select><img id="evidenceImage" class="evidence-image" alt="任务截图证据" hidden><div id="evidence"></div></section></section></div><p class="source-note space">任务由宿主模型推进。关闭网页不等于停止；结束宿主执行可能中断任务。停止操作会等待手机资源清理。</p></section>
<section id="settingsPage" class="page" hidden><div class="eyebrow">设置</div><h1>连接与执行</h1><section class="setting"><h2>执行方式</h2><p id="hostModeNotice" hidden>由当前宿主模型理解任务、查看截图并下发动作。无需另配模型。请保持宿主任务运行；网页提交后等待宿主接手。</p><div id="byokSettings"><h2>视觉模型</h2><p class="muted">OpenGUI 使用你配置的视觉模型执行手机任务，不借用宿主账号。最近保存并验证的配置用于新任务，无需每次选择。修改配置只影响新任务。</p><ul id="profiles"></ul><form id="modelForm"><label for="endpoint">API 基础地址</label><input id="endpoint" type="url" required placeholder="https://gateway.example/v1"><label for="protocol">协议</label><select id="protocol"><option value="openai-completions">Chat Completions</option><option value="openai-responses">Responses</option></select><label for="model">模型名</label><input id="model" required><label for="secret">API 凭据</label><input id="secret" type="password" autocomplete="off" required><p><small>凭据保存到 macOS 钥匙串。连接检查会发送一张测试图片。</small></p><div class="row space"><button class="primary">验证并保存</button></div><p id="modelStatus" role="status"></p></form></div></section><section class="setting"><h2>本地服务</h2><p class="muted">手机操作与记录由本地服务维护，任务决策由宿主模型提供。宿主会接收执行所需的截图。</p><p><small>用量有数据才显示。缺失的 Token 与费用记为未知。</small></p></section><section class="setting"><h2>连接手机</h2><p class="muted">通过 USB 连接 Android 手机并授权调试。</p><a href="#guide">查看连接指南 →</a></section></section>
<section id="guidePage" class="page" hidden><a class="back" href="#home">← 返回工作台</a><div class="eyebrow">使用指南</div><h1>从连接手机，到完成任务</h1><div id="guideSteps"></div></section>
<section id="missingPage" class="page" hidden><h1>没有找到这个记录</h1><p class="muted">记录可能属于另一个宿主，请确认当前工作台。</p><a href="#home">返回首页 →</a></section>
</main><div id="toast" role="status" aria-live="polite"></div><footer><span>OpenGUI · 本机手机任务工作台</span><a href="#guide">用户故事与接入说明</a></footer><script>SCRIPT</script></body></html>`.replace("STYLES", workbenchStyles).replace("SCRIPT", workbenchScript + nativeBridgeScript)
