import { workbenchStyles } from "./styles.ts"
import { workbenchScript } from "./script.ts"
import { nativeBridgeScript } from "./native-bridge.ts"
/** Static shell; runtime values are inserted with textContent. */
export const workbenchPage = String.raw`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OpenGUI 手机工作台</title><style>STYLES</style></head><body>
<a class="skip" href="#main">跳到主要内容</a><header><a class="brand" href="#home">OpenGUI<small id="host"></small></a><nav aria-label="主要导航"><button id="new" type="button">新任务</button><a href="#tasks" id="historyToggle">任务</a></nav><a href="#settings" id="settingsToggle" class="settings">模型设置</a></header><div id="error" class="notice" role="alert"></div><main id="main" tabindex="-1">
<section id="homePage" class="page"><div class="workspace"><div class="workspace-main"><section id="workspaceEmpty"><h1>开始任务</h1><div class="head"><h2>实时画面</h2><a href="#guide">连接设备</a></div><div id="homeDevices" class="grid device-grid"></div><div id="examples" class="examples"></div></section>
<section id="taskPage" class="page" hidden><h1 id="goalView"></h1><details id="goalDetails" class="goal-details" hidden><summary>查看完整任务目标</summary><p id="fullGoal"></p></details><p id="taskMeta" class="meta"></p><div class="row task-controls"><span id="state" class="pill" aria-live="polite"></span><button id="stop" class="danger">停止任务</button><button id="reuse" hidden>用此任务创建草稿</button><button id="export">导出记录</button></div><div id="taskNotice" class="notice" hidden></div><section id="branches" class="section" hidden><h2>执行分支</h2><div id="branchCards" class="grid"></div></section><div class="detail-grid"><section class="task-screen"><div class="head"><h2>实时画面</h2></div><p id="empty" class="empty">等待画面…</p><iframe id="viewer" title="Android 实时画面" hidden></iframe></section><section class="task-content"><h2>结果</h2><p id="result" aria-live="polite"></p><p id="checks" class="muted"></p><small id="usage"></small><h2>步骤</h2><ol id="timeline" class="timeline" aria-label="执行步骤"></ol><section id="steering"><h2>补充指令</h2><label class="sr-only" for="instruction">补充指令</label><textarea id="instruction" maxlength="8000" placeholder="补充要求"></textarea><div class="row space"><button id="steer">提交补充</button></div></section><section class="evidence"><h3>证据</h3><p id="noEvidence" class="no-evidence">暂无截图</p><label id="evidenceLabel" for="evidenceSelect" hidden>选择记录的画面</label><select id="evidenceSelect" hidden></select><img id="evidenceImage" class="evidence-image" alt="任务截图证据" hidden><div id="evidence"></div></section></section></div></section>
<form id="taskForm" class="composer"><label class="sr-only" for="goal">任务目标</label><textarea id="goal" required maxlength="8000" placeholder="描述要在手机上完成的任务"></textarea><div class="row submit-row"><span id="composerModel" class="muted"></span><button id="configureModel" type="button" class="primary" hidden>配置模型</button><button id="submit" type="submit" class="primary">开始任务</button></div></form></div><aside class="workspace-rail" aria-label="任务队列与历史"><section><h2>进行中 / 排队</h2><div id="queueTasks" class="workspace-task-list"></div></section><section><h2>历史</h2><div id="pastTasks" class="workspace-task-list"></div></section></aside></div></section>
<section id="devicesPage" class="page" hidden><div class="head"><h1>设备</h1><a href="#guide">连接指南</a></div><div id="allDevices" class="grid device-grid space"></div></section>
<section id="devicePage" class="page" hidden><a class="back" href="#devices">← 所有设备</a><div class="head"><h1 id="deviceTitle">手机画面</h1><span id="deviceStatus" class="pill"></span></div><div class="live-device"><p id="previewEmpty" class="empty">正在连接画面…</p><iframe id="deviceViewer" title="设备实时画面" hidden></iframe></div><div class="row space"><button id="useDevice" class="primary">在这台手机上创建任务</button></div></section>
<section id="tasksPage" class="page" hidden><div class="head"><h1>任务</h1><a href="#home">新任务</a></div><div id="filters" class="filters"><button data-filter="all" aria-pressed="true">全部</button><button data-filter="active" aria-pressed="false">进行中</button><button data-filter="done" aria-pressed="false">已结束</button></div><div id="history" class="task-list history-list"></div></section>
<section id="settingsPage" class="page" hidden><h1>模型设置</h1><section class="setting"><p id="hostModeNotice" hidden>当前使用宿主模型。</p><div id="byokSettings"><h2>模型</h2><ul id="profiles"></ul><form id="modelForm"><label for="endpoint">API 基础地址</label><input id="endpoint" type="url" required placeholder="https://gateway.example/v1"><label for="protocol">协议</label><select id="protocol"><option value="openai-completions">Chat Completions</option><option value="openai-responses">Responses</option></select><label for="model">模型名</label><input id="model" required><label for="secret">API 凭据</label><input id="secret" type="password" autocomplete="off" required><p><small>凭据保存到 macOS 钥匙串；验证会发送一张测试图片。</small></p><div class="row space"><button class="primary" type="submit">验证并保存</button></div><p id="modelStatus" role="status"></p></form></div></section></section>
<section id="guidePage" class="page" hidden><a class="back" href="#home">← 返回工作台</a><h1>连接指南</h1><div id="guideSteps"></div></section>
<section id="missingPage" class="page" hidden><h1>记录不存在</h1><a href="#home">返回首页 →</a></section>
</main><div id="toast" role="status" aria-live="polite"></div><footer><span>OpenGUI</span><a href="#guide">连接指南</a></footer><script>SCRIPT</script></body></html>`.replace("STYLES", workbenchStyles).replace("SCRIPT", workbenchScript + nativeBridgeScript)
