/** Browser controller. Untrusted model and task text never becomes markup. */
export const workbenchScript = String.raw`
const $=id=>document.getElementById(id), base=location.pathname;
const phases={queued:'排队中',preparing:'等待真实首帧',running:'正在执行',waiting:'等待用户处理',stopping:'正在停止并清理',completed:'已完成',blocked:'受阻',failed:'失败',cancelled:'已停止',unknown:'结果未知'};
const clarifying=t=>t.phase==='blocked'&&t.group?.plan?.kind==='clarification';
function phaseLabel(t){if(clarifying(t))return '等待补充信息';if(t.phase==='preparing'){if(t.group)return executionMode==='host'?'等待宿主规划':'正在规划任务';return t.viewerUrl?'等待真实首帧':'正在连接手机画面'}return phases[t.phase]||t.phase}
const active=t=>clarifying(t)||['queued','preparing','running','waiting','stopping'].includes(t.phase);
let nativeRequestToken='',tasks=[],phones=[],profiles=[],executionMode='host',embedOrigin='',host='',sharedRoute='',selected=null,filter='all',busy=false,deviceBusy=false,requestId=crypto.randomUUID(),screenHidden=false,previewDevice=null,previewUrl='',deviceSignature='',taskSignature='',evidenceSignature='',eventSequence='',toastTimer,preferredDevice,draftTimer,draftLoaded=false;const cardStreams=new Map();
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
function button(text,fn,cls=''){const b=node('button',text,cls);b.type='button';b.onclick=()=>action(fn);return b}
function link(text,route){const a=node('a',text);a.href='#'+route;return a}
function notify(text){$('toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',4500)}
async function api(route,data){const r=await fetch(base+route,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json',...(nativeRequestToken?{'X-OpenGUI-Request-Token':nativeRequestToken}:{})},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error||'请求失败，请重试');return v}
async function action(fn){$('error').textContent='';try{return await fn()}catch(e){$('error').textContent=e.message}}
function route(){const raw=decodeURIComponent(location.hash.slice(1)||'home');if(/^[a-f0-9-]{36}$/.test(raw))return 'task/'+raw;return raw}
function shareRoute(){const current=route();if(current!==sharedRoute&&host==='dsh'&&embedOrigin&&window.parent!==window){window.parent.postMessage({type:'opengui-workbench-route',route:current},embedOrigin);sharedRoute=current}}
function go(to){if(route()===to)render();else location.hash=to}
function options(el,items,key,label,placeholder){const old=el.value;const signature=JSON.stringify(items.map(x=>[x[key],label(x)]));if(el.dataset.items===signature)return;el.dataset.items=signature;el.replaceChildren();if(placeholder){const o=node('option',placeholder);o.value='';el.append(o)}for(const item of items){const o=node('option',label(item));o.value=item[key];el.append(o)}if(items.some(i=>i[key]===old))el.value=old}
const protocolLabel=p=>p==='openai-responses'?'Responses':'Chat Completions';
function displayError(message){return typeof message==='string'&&message.startsWith('device_busy:')?'手机正被其他任务占用。请先在对应宿主中停止该任务，确认停止后再重试。（device_busy）':message}
function displaySummary(t){if(t.error?.startsWith('device_busy:'))return displayError(t.error);const children=t.group?tasks.filter(c=>c.parentId===t.id):[];return children.some(c=>c.error?.startsWith('device_busy:'))?children.map(c=>c.deviceName+': '+displaySummary(c)).join('\n'):t.summary}
function source(t){return t.owner==='workbench'?'网页':({codex:'Codex',workbuddy:'WorkBuddy',dsh:'DSH'}[host]||host)}
function deviceLabel(d){if(!d.connected)return '已断开';if(!d.authorized)return '待授权';return tasks.some(t=>t.deviceId===d.id&&active(t))?'占用中':'空闲'}
function drawRows(target,list){target.replaceChildren();if(!list.length){target.append(node('p','还没有符合条件的任务。在首页创建，或从宿主会话发起。','muted'));return}for(const t of list){const row=node('article',undefined,'task-row'),body=node('div'),actions=node('div',undefined,'row');body.append(link(t.goal,'task/'+t.id));body.firstChild.className='task-title';body.append(node('div',source(t)+' · '+t.deviceName+' · '+new Date(t.createdAt).toLocaleString('zh-CN'),'meta'));actions.append(node('span',phaseLabel(t),'pill'),link('查看','task/'+t.id));if(active(t))actions.append(button('停止',async()=>{await api('manage',{taskId:t.id,action:'stop'});await refresh()},'danger'));row.append(body,actions);target.append(row)}}
function drawDevices(target,list){target.replaceChildren();if(!list.length){const empty=node('div',undefined,'empty');empty.append(node('h3','还没有连接手机'),node('p','可以先浏览任务示例。准备好后，用 USB 连接手机并允许调试。','muted'),link('查看连接指南 →','guide'));target.append(empty);return}for(const d of list){const card=node('article',undefined,'device'),head=node('div',undefined,'row spread'),preview=node('div',undefined,'device-preview');head.append(node('h3',d.name),node('span',deviceLabel(d),'pill'));preview.append(node('p',d.authorized&&d.connected?'已连接，可查看实时画面':d.connected?'请在实体手机上允许 USB 调试':'请重新连接手机，任务记录仍会保留'));const task=tasks.find(t=>t.deviceId===d.id&&active(t)),foot=node('div',undefined,'device-foot');foot.append(task?link(task.goal,'task/'+task.id):node('span','未分配任务','muted'));const actions=node('div',undefined,'device-actions');const watch=button(cardStreams.has(d.id)?'隐藏画面':'查看画面',async()=>{if(cardStreams.has(d.id)){cardStreams.delete(d.id)}else{const value=await api('preview',{deviceId:d.id});cardStreams.set(d.id,value.url)}deviceSignature='';render()});if(cardStreams.has(d.id)){preview.replaceChildren();preview.className='card-stream';const frame=node('iframe');frame.title=d.name+' 实时画面';frame.src=cardStreams.get(d.id);preview.append(frame)}watch.disabled=!d.authorized||!d.connected;actions.append(watch,button('放大查看 →',()=>openPreview(d.id)));if(!d.connected||!d.authorized)actions.lastChild.disabled=true;card.append(head,preview,foot,actions);target.append(card)}}
async function devices(){if(deviceBusy)return;deviceBusy=true;try{phones=await api('devices');render()}finally{deviceBusy=false}}
function render(){const r=route(),kind=r.split('/')[0],id=r.split('/')[1];selected=kind==='task'?id:null;const task=tasks.find(t=>t.id===selected);const name=kind==='task'&&!task?'missing':kind==='device'&&!phones.some(d=>d.id===id)?'missing':kind;const page=$(name+'Page')||$('missingPage');for(const el of document.querySelectorAll('.page'))el.hidden=el!==page;document.querySelectorAll('header a').forEach(a=>a.setAttribute('aria-current',a.hash==='#'+({task:'tasks',device:'devices'}[kind]||kind)?'page':'false'));$('host').textContent=({workbuddy:'WorkBuddy',codex:'Codex',dsh:'DSH'}[host]||host);
const ready=phones.filter(d=>d.connected&&d.authorized);$('submit').textContent=!ready.length?'连接手机并继续':executionMode!=='host'&&!profiles.length?'配置视觉模型':'开始任务';$('setupHint').textContent=!ready.length?'草稿会保留，连接并授权手机后即可继续。':executionMode!=='host'&&!profiles.length?'首次使用需要连接视觉模型，草稿会保留。':'由宿主模型执行 · 自动调配设备 · 提交后等待宿主接手。';$('deviceSummary').textContent=ready.length+' 台就绪 · '+phones.filter(d=>d.connected&&!d.authorized).length+' 台待授权 · '+phones.filter(d=>tasks.some(t=>t.deviceId===d.id&&active(t))).length+' 台占用';
const ds=JSON.stringify([phones,tasks.filter(active).map(t=>[t.id,t.phase,t.deviceId])]);if(ds!==deviceSignature){deviceSignature=ds;drawDevices($('homeDevices'),phones.slice(0,3));drawDevices($('allDevices'),phones)}
const ts=JSON.stringify([tasks.map(t=>[t.id,t.sequence]),filter]);if(ts!==taskSignature){taskSignature=ts;drawRows($('recentTasks'),tasks.filter(t=>!t.parentId).slice(0,3));drawRows($('history'),tasks.filter(t=>!t.parentId&&(filter==='all'||filter==='active'&&active(t)||filter==='done'&&!active(t))))}
for(const b of $('filters').children)b.setAttribute('aria-pressed',String(b.dataset.filter===filter));
if(kind==='task'&&task)renderTask(task);if(kind==='device'){const d=phones.find(d=>d.id===id);if(d){$('deviceTitle').textContent=d.name;$('deviceStatus').textContent=deviceLabel(d);$('previewEmpty').textContent=!d.connected?'手机已断开，请重新连接。':!d.authorized?'请在手机上允许 USB 调试。':'点击下方「显示画面」查看实时视频。';$('deviceViewer').hidden=previewDevice!==id||!previewUrl;$('previewEmpty').hidden=!$('deviceViewer').hidden;if(previewDevice===id&&previewUrl&&$('deviceViewer').src!==previewUrl)$('deviceViewer').src=previewUrl;$('hidePreview').textContent=previewUrl&&previewDevice===id?'隐藏画面':'显示画面'}}}
function renderTask(t){const first=t.goal.split(/[。！？\n]/u)[0],short=t.goal.length<=64?t.goal:first&&first.length<=64?first:'手机任务';$('goalView').textContent=short;$('goalDetails').hidden=short===t.goal;if($('goalDetails').dataset.task!==t.id){$('goalDetails').open=false;$('goalDetails').dataset.task=t.id}$('fullGoal').textContent=t.goal;$('taskMeta').textContent='来源 '+source(t)+' · '+t.deviceName+' · '+new Date(t.createdAt).toLocaleString('zh-CN')+' · 执行模型 '+t.modelProfile.model;$('state').textContent=phaseLabel(t)+' · '+t.steps+' 步';$('stop').hidden=!active(t);$('stop').disabled=t.phase==='stopping';$('reuse').hidden=active(t);$('steering').hidden=!active(t);$('steer').disabled=!['queued','preparing','running','waiting'].includes(t.phase);$('result').textContent=displaySummary(t)|| (active(t)?'正在执行，结果将在核验后显示。':'没有已核验的完成结果。');$('checks').textContent='成功标准：'+t.successCriteria+(t.checks.length?' · '+t.checks.map(c=>({passed:'已满足',failed:'未满足',unknown:'证据不足'})[c.status]).join(' / '):' · 等待终态核验');$('usage').textContent=t.usage?'Token 输入 '+t.usage.input+' / 输出 '+t.usage.output+' · 费用未知':'Token 用量未知 · 费用未知';const notices={waiting:t.summary,queued:'等待这台手机的前序任务结束，不抢占已有任务。',preparing:t.group?(executionMode==='host'?'任务已接收，等待宿主规划和分配手机。请保持宿主任务运行。':'正在理解任务并分配手机。'):t.viewerUrl?'请保持画面可见，等待真实首帧后才会开始操作。':'正在连接手机并准备画面，尚未开始操作。',stopping:'已请求停止，正在等待在途操作结束与资源清理。',cancelled:'任务已停止，不会自动重新执行。',unknown:'执行结果未知。请检查手机与已保存的证据，系统不会重放动作。',blocked:'任务受阻，请检查失败原因，处理后可创建新任务。',failed:'任务失败，请检查记录与设备状态。'};const note=(clarifying(t)?'请在下方补充信息，宿主会继续规划同一个任务，无需重新创建。':notices[t.phase]||'')+(t.error?' '+displayError(t.error):'');$('taskNotice').textContent=note;$('taskNotice').hidden=!note;
$('instruction').placeholder=clarifying(t)?'请回答上方问题，补充后继续安排任务。':t.phase==='waiting'?'处理后在这里回复，执行器会重新观察原手机。':'补充要求会在下一次决策时生效。';$('steer').textContent=t.phase==='waiting'?'已处理，继续':'提交补充';const group=!!t.group,needsClarification=clarifying(t);$('branches').hidden=!group;document.querySelector('.task-screen').hidden=group||!active(t);document.querySelector('.detail-grid').classList.toggle('result-only',group||!active(t));document.querySelector('.task-content .evidence').hidden=false;$('steering').hidden=!active(t)&&!needsClarification;$('steer').disabled=group?!(['running','waiting','blocked'].includes(t.phase)):!['queued','preparing','running','waiting'].includes(t.phase);$('stop').hidden=!active(t)&&!needsClarification;if(group){const children=tasks.filter(c=>c.parentId===t.id).reverse(),cards=$('branchCards');if(cards.dataset.parent!==t.id){cards.replaceChildren();cards.dataset.parent=t.id;delete cards.dataset.focused}for(const c of children){let card=[...cards.children].find(el=>el.dataset.child===c.id);if(!card){card=node('article',undefined,'device');card.dataset.child=c.id;const title=link(c.goal,'task/'+c.id);title.className='task-title';card.append(title,node('p',undefined,'branch-status'));const iframe=node('iframe');iframe.title=c.deviceName+' 分支实时画面';card.append(iframe);cards.append(card)}card.querySelector('.branch-status').textContent=c.deviceName+' · '+phaseLabel(c);const frame=card.querySelector('iframe');const live=active(c)&&!!c.viewerUrl;frame.hidden=!live;if(live&&frame.src!==c.viewerUrl)frame.src=c.viewerUrl;else if(!live)frame.removeAttribute('src')}if(!children.length&&cards.children.length===0)cards.textContent=t.summary;if(children.length&&cards.firstChild?.nodeType===3)cards.firstChild.remove();const waiting=children.find(c=>c.phase==='preparing'&&c.viewerUrl);if(waiting&&cards.dataset.focused!==waiting.id){cards.dataset.focused=waiting.id;[...cards.children].find(el=>el.dataset.child===waiting.id)?.querySelector('iframe')?.scrollIntoView({block:'center',behavior:'instant'})}}
const liveTask=!group&&active(t)&&!!t.viewerUrl;$('viewer').hidden=screenHidden||!liveTask;$('empty').hidden=!$('viewer').hidden;$('empty').textContent=screenHidden?'画面已隐藏，任务继续执行。':'等待手机画面，步骤和结果会持续更新。';$('toggleScreen').textContent=screenHidden?'显示画面':'隐藏画面';if(liveTask&&$('viewer').src!==t.viewerUrl)$('viewer').src=t.viewerUrl;else if(!liveTask)$('viewer').removeAttribute('src');
const list=taskEvidence(t),signature=JSON.stringify([t.id,list]);if(signature!==evidenceSignature){const previous=$('evidenceSelect').value,sameTask=$('evidenceSelect').dataset.task===t.id;evidenceSignature=signature;$('evidenceSelect').dataset.task=t.id;options($('evidenceSelect'),list,'key',e=>(group?e.deviceName+' · ':'')+new Date(e.capturedAt).toLocaleTimeString('zh-CN')+' · '+e.width+' × '+e.height+(e.checked?' · 核验引用':''));$('evidenceSelect').hidden=!list.length;$('evidenceLabel').hidden=!list.length;$('noEvidence').hidden=!!list.length;if(list.length)$('evidenceSelect').value=!active(t)&&list.some(e=>e.checked)?list.filter(e=>e.checked).at(-1).key:sameTask&&list.some(e=>e.key===previous)?previous:list.at(-1).key;showEvidence(t)}
if(eventSequence!==t.id+':'+t.sequence){eventSequence=t.id+':'+t.sequence;void action(async()=>{const id=t.id,events=await api('events/'+id);if(selected!==id)return;$('timeline').replaceChildren();const names={user_help_requested:'等待用户处理',user_help_resolved:'用户已处理，重新观察',accepted:'任务已接收',plan_recorded:'执行分支已规划',branch_created:'执行分支已创建',clarification_requested:'等待业务信息补充',planning_interrupted:'规划或分配中断',branch_progress:'分支状态更新',queued:'进入等待队列',preparing:'准备执行',started:'开始执行',display_wait:'等待真实可见首帧',observation:'已记录手机画面',confirmation_requested:'等待确认操作',confirmation_allowed:'操作已获确认',confirmation_declined:'操作未获确认',action_rejected:'动作已拒绝',result_proposed:'正在核验结果',action_intent:'执行动作',action_delivered:'动作已送达',action_outcome_unknown:'动作结果未知，等待重新观察',instruction_accepted:'补充指令已记录',stop_requested:'收到停止请求',settled:'任务结束',interrupted:'执行已中断'};for(const e of events){if(!names[e.event])continue;const li=node('li',names[e.event]+(e.action?' · '+e.action:''));li.append(node('small',new Date(e.at).toLocaleTimeString('zh-CN')));$('timeline').append(li)}})}}
function taskEvidence(t){if(!t)return [];const owners=t.group?tasks.filter(c=>c.parentId===t.id):[t];return owners.flatMap(owner=>owner.evidence.map(e=>({...e,taskId:owner.id,deviceName:owner.deviceName,key:owner.id+':'+e.id,checked:owner.checks.some(c=>c.evidenceId===e.id)}))).sort((a,b)=>a.capturedAt.localeCompare(b.capturedAt)||a.key.localeCompare(b.key))}
function showEvidence(t=tasks.find(t=>t.id===selected)){const e=taskEvidence(t).find(e=>e.key===$('evidenceSelect').value);$('evidence').replaceChildren();$('evidenceImage').hidden=!e;if(!e){$('evidenceImage').removeAttribute('src');return}const url=base+'evidence/'+e.taskId+'/'+e.file;$('evidenceImage').width=e.width;$('evidenceImage').height=e.height;$('evidenceImage').src=url;$('evidenceImage').alt=e.deviceName+' · '+new Date(e.capturedAt).toLocaleString('zh-CN')+' 截图证据';const a=node('a','打开原始截图 ↗');a.href=url;a.target='_blank';a.rel='noopener';$('evidence').append(a)}
async function openPreview(id){const d=phones.find(d=>d.id===id);if(!d?.connected||!d.authorized)throw Error('请先连接手机并允许 USB 调试。');previewDevice=id;previewUrl=cardStreams.get(id)||'';go('device/'+id);if(previewUrl){render();return}$('previewEmpty').textContent='正在准备实时画面…';const value=await api('preview',{deviceId:id});if(previewDevice!==id)return;previewUrl=value.url;render()}
async function refresh(){if(busy)return;busy=true;try{const data=await api('state');nativeRequestToken=data.nativeRequestToken||'';if(!draftLoaded){draftLoaded=true;if(!$('goal').value)$('goal').value=data.draft||''}tasks=data.tasks;profiles=data.profiles;executionMode=data.executionMode||'byok';embedOrigin=data.embedOrigin||'';$('byokSettings').hidden=executionMode==='host';$('hostModeNotice').hidden=executionMode!=='host';host=data.host;render();shareRoute();const signature=JSON.stringify(profiles.map(p=>[p.id,p.model,p.protocol]));if($('profiles').dataset.signature!==signature){$('profiles').dataset.signature=signature;$('profiles').replaceChildren();if(!profiles.length)$('profiles').append(node('li','尚未配置视觉模型','muted'));for(const p of profiles){const li=node('li');li.append(node('strong',p.model+(p.id===profiles.at(-1)?.id?' · 当前默认':'')),node('div',protocolLabel(p.protocol),'profile-protocol'));$('profiles').append(li)}}}finally{busy=false}}
new ResizeObserver(entries=>document.documentElement.style.setProperty('--header-height',entries[0].target.offsetHeight+'px')).observe(document.querySelector('header'));document.querySelector('.skip').onclick=e=>{e.preventDefault();$('main').focus();$('main').scrollIntoView({block:'start'})};
window.addEventListener('hashchange',()=>{screenHidden=false;eventSequence='';render();shareRoute();window.scrollTo(0,0)});
$('refresh').onclick=()=>action(devices);$('refreshDevices').onclick=()=>action(devices);$('new').onclick=()=>{requestId=crypto.randomUUID();preferredDevice=undefined;go('home')};$('evidenceSelect').onchange=()=>showEvidence();for(const b of $('filters').children)b.onclick=()=>{filter=b.dataset.filter;render()};$('toggleScreen').onclick=()=>{screenHidden=!screenHidden;render()};$('hidePreview').onclick=()=>action(async()=>{if(previewUrl){previewUrl='';$('deviceViewer').removeAttribute('src');render()}else await openPreview(route().split('/')[1])});$('useDevice').onclick=()=>{preferredDevice=route().split('/')[1];go('home');$('goal').focus()};
function saveDraft(){clearTimeout(draftTimer);return api('draft',{goal:$('goal').value})}
$('goal').oninput=()=>{clearTimeout(draftTimer);draftTimer=setTimeout(()=>action(saveDraft),300)};
window.addEventListener('pagehide',()=>{clearTimeout(draftTimer);void fetch(base+'draft',{method:'POST',headers:{'Content-Type':'application/json',...(nativeRequestToken?{'X-OpenGUI-Request-Token':nativeRequestToken}:{})},body:JSON.stringify({goal:$('goal').value}),keepalive:true}).catch(()=>{})});
$('taskForm').onsubmit=e=>{e.preventDefault();action(async()=>{await saveDraft();if(!phones.some(d=>d.authorized&&d.connected)){go('guide');return}if(executionMode!=='host'&&!profiles.length){go('settings');return}$('submit').disabled=true;try{const t=await api('run',{requestId,goal:$('goal').value,successCriteria:$('goal').value,...(preferredDevice?{deviceId:preferredDevice}:{})});if(executionMode==='host'&&host==='dsh'&&embedOrigin&&window.parent!==window)window.parent.postMessage({type:'opengui-task-accepted',taskId:t.id},embedOrigin);requestId=crypto.randomUUID();$('goal').value='';await saveDraft();tasks=[t,...tasks.filter(x=>x.id!==t.id)];go('task/'+t.id);await refresh();$('viewer').scrollIntoView({block:'center',behavior:'instant'});if(executionMode==='host'&&['workbuddy','codex'].includes(host))await window.openguiHostBridge?.continueTask(t)}finally{$('submit').disabled=false}})};
$('modelForm').onsubmit=e=>{e.preventDefault();const b=e.submitter;b.disabled=true;$('modelStatus').textContent='正在检查图片输入与工具调用能力…';action(async()=>{await api('model',{baseUrl:$('endpoint').value,protocol:$('protocol').value,model:$('model').value,secret:$('secret').value});$('secret').value='';$('modelStatus').textContent='连接已验证，凭据已保存到钥匙串。';await refresh();notify('模型已保存，可以返回首页开始任务。')}).finally(()=>{b.disabled=false;if($('error').textContent)$('modelStatus').textContent='连接检查失败，配置未保存。'})};
$('steer').onclick=()=>action(async()=>{const task=tasks.find(t=>t.id===selected),text=$('instruction').value.trim(),resume=task?.phase==='waiting'&&!text,wake=task&&(task.phase==='waiting'||clarifying(task));if(!text&&!resume)throw Error('请先填写补充要求。');const updated=await api('manage',{taskId:selected,action:resume?'resume':'steer',...(text?{text}:{})});if(wake&&executionMode==='host'&&host==='dsh'&&embedOrigin&&window.parent!==window)window.parent.postMessage({type:'opengui-task-continued',taskId:updated.id,sequence:updated.sequence},embedOrigin);$('instruction').value='';notify('补充指令已记录');await refresh();if(wake&&executionMode==='host'&&['workbuddy','codex'].includes(host))await window.openguiHostBridge?.continueTask(updated)});$('stop').onclick=()=>action(async()=>{$('stop').disabled=true;try{await api('manage',{taskId:selected,action:'stop'});await refresh()}finally{render()}});$('reuse').onclick=()=>{const t=tasks.find(t=>t.id===selected);$('goal').value=t.goal;void action(saveDraft);preferredDevice=t.group?undefined:t.deviceId;requestId=crypto.randomUUID();go('home')};$('export').onclick=()=>action(async()=>{const t=tasks.find(t=>t.id===selected);const clean=t=>({id:t.id,goal:t.goal,successCriteria:t.successCriteria,device:t.deviceName,phase:t.phase,createdAt:t.createdAt,updatedAt:t.updatedAt,steps:t.steps,summary:t.summary,checks:t.checks,evidence:t.evidence,usage:t.usage??null});const record={...clean(t),...(t.group?{branches:tasks.filter(c=>c.parentId===t.id).map(clean)}:{})};const a=node('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));a.download='opengui-task-'+t.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
const examples=[['查看手机信息','读取 Android 版本和设备型号。','打开系统设置，查找 Android 版本和设备型号，不修改设置。','页面显示系统版本和设备型号，结果准确记录两项信息。'],['验证应用页面','检查指定页面是否按预期显示。','打开指定应用并检查目标页面。请先向我确认应用和要检查的页面。','保存目标页面截图，说明实际显示的内容与检查结果。'],['查找页面内容','在手机上查找并核对指定信息。','在指定应用中查找信息。请先向我确认应用、关键词和核对要求。','结果包含查到的信息与对应画面证据。']];for(const [title,desc,goal,criteria] of examples){const b=button('',()=>{$('goal').value=goal;void action(saveDraft);$('goal').focus();$('taskForm').scrollIntoView({block:'center',behavior:'instant'})},'example');b.append(node('strong',title+' ↗'),node('span',desc));$('examples').append(b)}
const steps=[['安装与打开','安装对应宿主的 OpenGUI 插件。Codex、WorkBuddy 和 DSH 分别使用自己的配置、后台和任务记录。'],['宿主执行','使用当前宿主的模型，无需另配模型。请在宿主会话打开工作台并保持任务运行；网页提交的目标由宿主接手。'],['连接手机','用 USB 数据线连接 Android 手机与电脑。解锁手机，开启开发者选项与 USB 调试，在手机弹窗中允许这台电脑调试。'],['查看手机','连接并授权后可查看真实画面。系统按任务自动安排设备，业务账号不明确时才澄清。'],['下达任务','在首页或宿主会话描述任务，把需要核对的结果写在任务里。提交后保持工作台画面可见，真实首帧通过后才会执行。'],['观察与停止','在任务详情同屏查看手机、步骤和状态。可以补充指令或明确停止；关闭网页不等于停止；结束宿主执行可能中断任务。'],['结果与后续','完成后查看成功标准检查和截图证据。断连、受阻或结果未知不会被当成完成，也不会自动重放动作。可保留记录并创建新的任务草稿。']];steps.forEach(([title,text],i)=>{const section=node('section',undefined,'guide-step'),body=node('div');body.append(node('h2',title),node('p',text));section.append(node('span',String(i+1).padStart(2,'0'),'number'),body);$('guideSteps').append(section)});
action(async()=>{await refresh();await devices()});setInterval(()=>refresh().catch(e=>$('error').textContent=e.message),1500);setInterval(()=>devices().catch(e=>$('error').textContent=e.message),10000);
`
