/** Browser controller. Untrusted model and task text never becomes markup. */
export const workbenchScript = String.raw`
const $=id=>document.getElementById(id), base=location.pathname, context=location.search;
const phases={queued:'排队中',preparing:'等待真实首帧',running:'正在执行',waiting:'等待用户处理',stopping:'正在停止并清理',completed:'已完成',blocked:'受阻',failed:'失败',cancelled:'已停止',unknown:'结果未知'};
const clarifying=t=>t.phase==='blocked'&&t.group?.plan?.kind==='clarification';
function phaseLabel(t){if(clarifying(t))return '等待补充信息';if(t.phase==='preparing'){if(t.group)return executionMode==='host'?'等待宿主规划':'正在规划任务';return t.viewerUrl?'等待真实首帧':'正在连接手机画面'}return phases[t.phase]||t.phase}
const active=t=>clarifying(t)||['queued','preparing','running','waiting','stopping'].includes(t.phase);
let tasks=[],phones=[],profiles=[],executionMode='host',embedOrigin='',host='',sharedRoute='',selected=null,filter='all',busy=false,deviceBusy=false,requestId=crypto.randomUUID(),initialTaskSelection=false,previewDevice=null,previewUrl='',deviceSignature='',taskSignature='',evidenceSignature='',eventSequence='',toastTimer,preferredDevice,draftTimer,draftLoaded=false;const cardStreams=new Map(),previewPending=new Set();
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
function button(text,fn,cls=''){const b=node('button',text,cls);b.type='button';b.onclick=()=>action(fn);return b}
function link(text,route){const a=node('a',text);a.href='#'+route;return a}
function notify(text){$('toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',4500)}
async function api(route,data){const r=await fetch(base+route+context,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error||'请求失败，请重试');return v}
async function action(fn){$('error').textContent='';try{return await fn()}catch(e){$('error').textContent=e.message}}
function route(){const raw=decodeURIComponent(location.hash.slice(1)||'home');if(/^[a-f0-9-]{36}$/.test(raw))return 'task/'+raw;return raw}
function shareRoute(){const current=route();if(current!==sharedRoute&&host==='dsh'&&embedOrigin&&window.parent!==window){window.parent.postMessage({type:'opengui-workbench-route',route:current},embedOrigin);sharedRoute=current}}
function go(to){if(route()===to)render();else location.hash=to}
function options(el,items,key,label,placeholder){const old=el.value;const signature=JSON.stringify(items.map(x=>[x[key],label(x)]));if(el.dataset.items===signature)return;el.dataset.items=signature;el.replaceChildren();if(placeholder){const o=node('option',placeholder);o.value='';el.append(o)}for(const item of items){const o=node('option',label(item));o.value=item[key];el.append(o)}if(items.some(i=>i[key]===old))el.value=old}
const protocolLabel=p=>p==='openai-responses'?'Responses':'Chat Completions';
function displayError(message){return typeof message==='string'&&message.startsWith('device_busy:')?'手机正被其他任务占用。请先在对应宿主中停止该任务，确认停止后再重试。（device_busy）':message}
function displaySummary(t){if(t.error?.startsWith('device_busy:'))return displayError(t.error);const children=t.group?tasks.filter(c=>c.parentId===t.id):[];return children.some(c=>c.error?.startsWith('device_busy:'))?children.map(c=>c.deviceName+': '+displaySummary(c)).join('\n'):t.summary}
function source(t){return t.owner==='workbench'?'网页':({codex:'Codex',workbuddy:'WorkBuddy',dsh:'DSH'}[host]||host)}
function deviceLabel(d){if(!d.connected)return '已断开';if(!d.authorized)return '待授权';return tasks.some(t=>t.deviceId===d.id&&active(t))?'占用中':'空闲'}
function drawRows(target,list){target.replaceChildren();if(!list.length){target.append(node('p','暂无任务','muted'));return}for(const t of list){const row=node('article',undefined,'task-row'),body=node('div'),actions=node('div',undefined,'row');body.append(link(t.goal,'task/'+t.id));body.firstChild.className='task-title';body.append(node('div',source(t)+' · '+t.deviceName+' · '+new Date(t.createdAt).toLocaleString('zh-CN'),'meta'));actions.append(node('span',phaseLabel(t),'pill'),link('查看','task/'+t.id));if(active(t))actions.append(button('停止',async()=>{await api('manage',{taskId:t.id,action:'stop'});await refresh()},'danger'));row.append(body,actions);target.append(row)}}
function drawWorkspaceRows(target,list){target.replaceChildren();for(const t of list){const card=link('', 'task/'+t.id);card.className='workspace-task-card';card.dataset.task=t.id;const header=node('div',undefined,'row spread');header.append(node('span',phaseLabel(t),'pill'),node('time',new Date(t.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),'muted'));card.append(header,node('strong',t.goal,'task-title'),node('small',t.deviceName));target.append(card)}if(!list.length)target.append(node('p','暂无任务','muted'))}
function drawDevices(target,list){target.replaceChildren();if(!list.length){target.append(node('p','暂无设备','muted'));return}for(const d of list){const card=node('article',undefined,'device'),head=node('div',undefined,'row spread'),title=node('h3'),preview=node('div',undefined,'device-preview');title.append(link(d.name,'device/'+d.id));head.append(title,node('span',deviceLabel(d),'pill'));if(d.connected&&d.authorized&&cardStreams.has(d.id)){preview.className='card-stream';const frame=node('iframe');frame.title=d.name+' 实时画面';frame.src=cardStreams.get(d.id);preview.append(frame)}else preview.append(node('p',!d.connected?'已断开':!d.authorized?'待授权':'正在连接画面…'));card.append(head,preview);const task=tasks.find(t=>t.deviceId===d.id&&active(t));if(task){const foot=node('div',undefined,'device-foot');foot.append(link(task.goal,'task/'+task.id));card.append(foot)}target.append(card)}}
function syncStreams(){const ready=new Set(phones.filter(d=>d.connected&&d.authorized).map(d=>d.id));for(const id of cardStreams.keys())if(!ready.has(id))cardStreams.delete(id);if(previewDevice&&!ready.has(previewDevice)){previewUrl='';$('deviceViewer').removeAttribute('src')}for(const id of ready){if(cardStreams.has(id)||previewPending.has(id))continue;previewPending.add(id);void api('preview',{deviceId:id}).then(value=>{if(phones.some(d=>d.id===id&&d.connected&&d.authorized)){cardStreams.set(id,value.url);if(previewDevice===id)previewUrl=value.url;deviceSignature='';render()}}).catch(()=>{}).finally(()=>previewPending.delete(id))}}
async function devices(){if(deviceBusy)return;deviceBusy=true;try{phones=await api('devices');syncStreams();render()}finally{deviceBusy=false}}
function render(){const r=route(),kind=r.split('/')[0],id=r.split('/')[1];selected=kind==='task'?id:null;const task=tasks.find(t=>t.id===selected);const name=kind==='task'&&!task?'missing':kind==='device'&&!phones.some(d=>d.id===id)?'missing':kind;const page=$(name+'Page')||$('missingPage');for(const el of document.querySelectorAll('.page'))el.hidden=el===$('homePage')?name!=='home'&&name!=='task':el===$('taskPage')?name!=='task':el!==page;$('workspaceEmpty').hidden=name==='task';document.querySelectorAll('header a').forEach(a=>a.setAttribute('aria-current',a.hash==='#'+({task:'tasks',device:'devices'}[kind]||kind)?'page':'false'));$('host').textContent=({workbuddy:'WorkBuddy',codex:'Codex',dsh:'DSH'}[host]||host);
const ready=phones.filter(d=>d.connected&&d.authorized);$('composerModel').textContent=executionMode==='host'?'宿主模型':profiles.at(-1)?.model||'未配置模型';$('submit').textContent=!ready.length?'连接手机并继续':executionMode!=='host'&&!profiles.length?'配置视觉模型':'开始任务';
const ds=JSON.stringify([phones,tasks.filter(active).map(t=>[t.id,t.phase,t.deviceId])]);if(ds!==deviceSignature){deviceSignature=ds;drawDevices($('homeDevices'),phones.slice(0,3));drawDevices($('allDevices'),phones)}
const ts=JSON.stringify([tasks.map(t=>[t.id,t.sequence]),filter]);if(ts!==taskSignature){taskSignature=ts;const roots=tasks.filter(t=>!t.parentId);drawWorkspaceRows($('queueTasks'),roots.filter(active));drawWorkspaceRows($('pastTasks'),roots.filter(t=>!active(t)));drawRows($('history'),tasks.filter(t=>!t.parentId&&(filter==='all'||filter==='active'&&active(t)||filter==='done'&&!active(t))))}
document.querySelectorAll('.workspace-task-card').forEach(el=>el.setAttribute('aria-current',el.dataset.task===selected?'true':'false'));for(const b of $('filters').children)b.setAttribute('aria-pressed',String(b.dataset.filter===filter));
if(kind==='task'&&task)renderTask(task);if(kind==='device'){const d=phones.find(d=>d.id===id);if(d){$('deviceTitle').textContent=d.name;$('deviceStatus').textContent=deviceLabel(d);$('previewEmpty').textContent=!d.connected?'已断开':!d.authorized?'等待 USB 调试授权':'正在连接画面…';$('deviceViewer').hidden=previewDevice!==id||!previewUrl;$('previewEmpty').hidden=!$('deviceViewer').hidden;if(previewDevice===id&&previewUrl&&$('deviceViewer').src!==previewUrl)$('deviceViewer').src=previewUrl;if($('deviceViewer').hidden)$('deviceViewer').removeAttribute('src')}}}
function renderTask(t){const first=t.goal.split(/[。！？\n]/u)[0],short=t.goal.length<=64?t.goal:first&&first.length<=64?first:'手机任务';$('goalView').textContent=short;$('goalDetails').hidden=short===t.goal;if($('goalDetails').dataset.task!==t.id){$('goalDetails').open=false;$('goalDetails').dataset.task=t.id}$('fullGoal').textContent=t.goal;$('taskMeta').textContent=source(t)+' · '+t.deviceName+' · '+new Date(t.createdAt).toLocaleString('zh-CN');$('state').textContent=phaseLabel(t)+' · '+t.steps+' 步';$('stop').hidden=!active(t);$('stop').disabled=t.phase==='stopping';$('reuse').hidden=active(t);$('steering').hidden=!active(t);$('steer').disabled=!['queued','preparing','running','waiting'].includes(t.phase);$('result').textContent=displaySummary(t)|| (active(t)?'执行中':'暂无结果');$('checks').textContent='成功标准：'+t.successCriteria+(t.checks.length?' · '+t.checks.map(c=>({passed:'已满足',failed:'未满足',unknown:'证据不足'})[c.status]).join(' / '):'');$('usage').textContent=t.usage?'Token 输入 '+t.usage.input+' / 输出 '+t.usage.output:'';const notices={waiting:t.summary,queued:'等待设备',preparing:t.group?'正在规划任务':t.viewerUrl?'等待首帧':'正在连接画面',stopping:'正在停止',cancelled:'已停止',unknown:'结果未知，请核对设备与证据',blocked:'任务受阻，请查看错误',failed:'任务失败，请查看记录'};const note=(clarifying(t)?'请补充任务信息':notices[t.phase]||'')+(t.error?' · '+displayError(t.error):'');$('taskNotice').textContent=note;$('taskNotice').hidden=!note;
$('instruction').placeholder=clarifying(t)?'补充任务信息':t.phase==='waiting'?'处理结果或补充要求':'补充要求';$('steer').textContent=t.phase==='waiting'?'已处理，继续':'提交补充';const group=!!t.group,needsClarification=clarifying(t);$('branches').hidden=!group;document.querySelector('.task-screen').hidden=group||!active(t);document.querySelector('.detail-grid').classList.toggle('result-only',group||!active(t));document.querySelector('.task-content .evidence').hidden=false;$('steering').hidden=!active(t)&&!needsClarification;$('steer').disabled=group?!(['running','waiting','blocked'].includes(t.phase)):!['queued','preparing','running','waiting'].includes(t.phase);$('stop').hidden=!active(t)&&!needsClarification;if(group){const children=tasks.filter(c=>c.parentId===t.id).reverse(),cards=$('branchCards');if(cards.dataset.parent!==t.id){cards.replaceChildren();cards.dataset.parent=t.id;delete cards.dataset.focused}for(const c of children){let card=[...cards.children].find(el=>el.dataset.child===c.id);if(!card){card=node('article',undefined,'device');card.dataset.child=c.id;const title=link(c.goal,'task/'+c.id);title.className='task-title';card.append(title,node('p',undefined,'branch-status'));const iframe=node('iframe');iframe.title=c.deviceName+' 分支实时画面';card.append(iframe);cards.append(card)}card.querySelector('.branch-status').textContent=c.deviceName+' · '+phaseLabel(c);const frame=card.querySelector('iframe');const live=active(c)&&!!c.viewerUrl;frame.hidden=!live;if(live&&frame.src!==c.viewerUrl)frame.src=c.viewerUrl;else if(!live)frame.removeAttribute('src')}if(!children.length&&cards.children.length===0)cards.textContent=t.summary;if(children.length&&cards.firstChild?.nodeType===3)cards.firstChild.remove();const waiting=children.find(c=>c.phase==='preparing'&&c.viewerUrl);if(waiting&&cards.dataset.focused!==waiting.id){cards.dataset.focused=waiting.id;[...cards.children].find(el=>el.dataset.child===waiting.id)?.querySelector('iframe')?.scrollIntoView({block:'center',behavior:'instant'})}}
const liveTask=!group&&active(t)&&!!t.viewerUrl;$('viewer').hidden=!liveTask;$('empty').hidden=liveTask;$('empty').textContent='等待画面…';if(liveTask&&$('viewer').src!==t.viewerUrl)$('viewer').src=t.viewerUrl;else if(!liveTask)$('viewer').removeAttribute('src');
const list=taskEvidence(t),signature=JSON.stringify([t.id,list]);if(signature!==evidenceSignature){const previous=$('evidenceSelect').value,sameTask=$('evidenceSelect').dataset.task===t.id;evidenceSignature=signature;$('evidenceSelect').dataset.task=t.id;options($('evidenceSelect'),list,'key',e=>(group?e.deviceName+' · ':'')+new Date(e.capturedAt).toLocaleTimeString('zh-CN')+' · '+e.width+' × '+e.height+(e.checked?' · 核验引用':''));$('evidenceSelect').hidden=!list.length;$('evidenceLabel').hidden=!list.length;$('noEvidence').hidden=!!list.length;if(list.length)$('evidenceSelect').value=!active(t)&&list.some(e=>e.checked)?list.filter(e=>e.checked).at(-1).key:sameTask&&list.some(e=>e.key===previous)?previous:list.at(-1).key;showEvidence(t)}
if(eventSequence!==t.id+':'+t.sequence){eventSequence=t.id+':'+t.sequence;void action(async()=>{const id=t.id,events=await api('events/'+id);if(selected!==id)return;$('timeline').replaceChildren();const names={user_help_requested:'等待用户处理',user_help_resolved:'用户已处理，重新观察',accepted:'任务已接收',plan_recorded:'执行分支已规划',branch_created:'执行分支已创建',clarification_requested:'等待业务信息补充',planning_interrupted:'规划或分配中断',branch_progress:'分支状态更新',queued:'进入等待队列',preparing:'准备执行',started:'开始执行',display_wait:'等待真实可见首帧',observation:'已记录手机画面',confirmation_requested:'等待确认操作',confirmation_allowed:'操作已获确认',confirmation_declined:'操作未获确认',action_rejected:'动作已拒绝',result_proposed:'正在核验结果',action_intent:'执行动作',action_delivered:'动作已送达',action_outcome_unknown:'动作结果未知，等待重新观察',instruction_accepted:'补充指令已记录',stop_requested:'收到停止请求',settled:'任务结束',interrupted:'执行已中断'};for(const e of events){if(!names[e.event])continue;const li=node('li',names[e.event]+(e.action?' · '+e.action:''));li.append(node('small',new Date(e.at).toLocaleTimeString('zh-CN')));$('timeline').append(li)}})}}
function taskEvidence(t){if(!t)return [];const owners=t.group?tasks.filter(c=>c.parentId===t.id):[t];return owners.flatMap(owner=>owner.evidence.map(e=>({...e,taskId:owner.id,deviceName:owner.deviceName,key:owner.id+':'+e.id,checked:owner.checks.some(c=>c.evidenceId===e.id)}))).sort((a,b)=>a.capturedAt.localeCompare(b.capturedAt)||a.key.localeCompare(b.key))}
function showEvidence(t=tasks.find(t=>t.id===selected)){const e=taskEvidence(t).find(e=>e.key===$('evidenceSelect').value);$('evidence').replaceChildren();$('evidenceImage').hidden=!e;if(!e){$('evidenceImage').removeAttribute('src');return}const url=base+'evidence/'+e.taskId+'/'+e.file;$('evidenceImage').width=e.width;$('evidenceImage').height=e.height;$('evidenceImage').src=url;$('evidenceImage').alt=e.deviceName+' · '+new Date(e.capturedAt).toLocaleString('zh-CN')+' 截图证据';const a=node('a','打开原始截图 ↗');a.href=url;a.target='_blank';a.rel='noopener';$('evidence').append(a)}
async function refresh(){if(busy)return;busy=true;try{const data=await api('state');if(!draftLoaded){draftLoaded=true;if(!$('goal').value)$('goal').value=data.draft||''}tasks=data.tasks;if(!initialTaskSelection){initialTaskSelection=true;const current=tasks.find(t=>!t.parentId&&active(t));if(!location.hash&&current)location.hash='task/'+current.id}profiles=data.profiles;executionMode=data.executionMode||'byok';embedOrigin=data.embedOrigin||'';$('byokSettings').hidden=executionMode==='host';$('hostModeNotice').hidden=executionMode!=='host';host=data.host;render();shareRoute();const signature=JSON.stringify(profiles.map(p=>[p.id,p.model,p.protocol]));if($('profiles').dataset.signature!==signature){$('profiles').dataset.signature=signature;$('profiles').replaceChildren();if(!profiles.length)$('profiles').append(node('li','尚未配置视觉模型','muted'));for(const p of profiles){const li=node('li');li.append(node('strong',p.model+(p.id===profiles.at(-1)?.id?' · 当前默认':'')),node('div',protocolLabel(p.protocol),'profile-protocol'));$('profiles').append(li)}}}finally{busy=false}}
new ResizeObserver(entries=>document.documentElement.style.setProperty('--header-height',entries[0].target.offsetHeight+'px')).observe(document.querySelector('header'));document.querySelector('.skip').onclick=e=>{e.preventDefault();$('main').focus();$('main').scrollIntoView({block:'start'})};
window.addEventListener('hashchange',()=>{eventSequence='';if(route().startsWith('device/')){previewDevice=route().split('/')[1];previewUrl=cardStreams.get(previewDevice)||'';syncStreams()}render();shareRoute();window.scrollTo(0,0)});
$('new').onclick=()=>{requestId=crypto.randomUUID();preferredDevice=undefined;go('home')};$('evidenceSelect').onchange=()=>showEvidence();for(const b of $('filters').children)b.onclick=()=>{filter=b.dataset.filter;render()};$('useDevice').onclick=()=>{preferredDevice=route().split('/')[1];go('home');$('goal').focus()};
function saveDraft(){clearTimeout(draftTimer);return api('draft',{goal:$('goal').value})}
$('goal').oninput=()=>{clearTimeout(draftTimer);draftTimer=setTimeout(()=>action(saveDraft),300)};
window.addEventListener('pagehide',()=>{clearTimeout(draftTimer);void fetch(base+'draft'+context,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:$('goal').value}),keepalive:true}).catch(()=>{})});
$('taskForm').onsubmit=e=>{e.preventDefault();action(async()=>{await saveDraft();if(!phones.some(d=>d.authorized&&d.connected)){go('guide');return}if(executionMode!=='host'&&!profiles.length){go('settings');return}$('submit').disabled=true;try{const t=await api('run',{requestId,goal:$('goal').value,successCriteria:$('goal').value,...(preferredDevice?{deviceId:preferredDevice}:{})});if(executionMode==='host'&&host==='dsh'&&embedOrigin&&window.parent!==window)window.parent.postMessage({type:'opengui-task-accepted',taskId:t.id},embedOrigin);requestId=crypto.randomUUID();$('goal').value='';await saveDraft();tasks=[t,...tasks.filter(x=>x.id!==t.id)];go('task/'+t.id);await refresh();if(executionMode==='host'&&['workbuddy','codex'].includes(host))await window.openguiHostBridge?.continueTask(t)}finally{$('submit').disabled=false}})};
$('modelForm').onsubmit=e=>{e.preventDefault();const b=e.submitter;b.disabled=true;$('modelStatus').textContent='正在检查图片输入与工具调用能力…';action(async()=>{await api('model',{baseUrl:$('endpoint').value,protocol:$('protocol').value,model:$('model').value,secret:$('secret').value});$('secret').value='';$('modelStatus').textContent='连接已验证，凭据已保存到钥匙串。';await refresh();notify('模型已保存，可以返回首页开始任务。')}).finally(()=>{b.disabled=false;if($('error').textContent)$('modelStatus').textContent='连接检查失败，配置未保存。'})};
$('steer').onclick=()=>action(async()=>{const task=tasks.find(t=>t.id===selected),text=$('instruction').value.trim(),resume=task?.phase==='waiting'&&!text,wake=task&&(task.phase==='waiting'||clarifying(task));if(!text&&!resume)throw Error('请先填写补充要求。');const updated=await api('manage',{taskId:selected,action:resume?'resume':'steer',...(text?{text}:{})});if(wake&&executionMode==='host'&&host==='dsh'&&embedOrigin&&window.parent!==window)window.parent.postMessage({type:'opengui-task-continued',taskId:updated.id,sequence:updated.sequence},embedOrigin);$('instruction').value='';notify('补充指令已记录');await refresh();if(wake&&executionMode==='host'&&['workbuddy','codex'].includes(host))await window.openguiHostBridge?.continueTask(updated)});$('stop').onclick=()=>action(async()=>{$('stop').disabled=true;try{await api('manage',{taskId:selected,action:'stop'});await refresh()}finally{render()}});$('reuse').onclick=()=>{const t=tasks.find(t=>t.id===selected);$('goal').value=t.goal;void action(saveDraft);preferredDevice=t.group?undefined:t.deviceId;requestId=crypto.randomUUID();go('home')};$('export').onclick=()=>action(async()=>{const t=tasks.find(t=>t.id===selected);const clean=t=>({id:t.id,goal:t.goal,successCriteria:t.successCriteria,device:t.deviceName,phase:t.phase,createdAt:t.createdAt,updatedAt:t.updatedAt,steps:t.steps,summary:t.summary,checks:t.checks,evidence:t.evidence,usage:t.usage??null});const record={...clean(t),...(t.group?{branches:tasks.filter(c=>c.parentId===t.id).map(clean)}:{})};const a=node('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));a.download='opengui-task-'+t.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
const examples=[['查看手机信息','打开系统设置，查找 Android 版本和设备型号，不修改设置。'],['验证应用页面','打开指定应用并检查目标页面。请先向我确认应用和要检查的页面。'],['查找页面内容','在指定应用中查找信息。请先向我确认应用、关键词和核对要求。']];for(const [title,goal] of examples){const b=button('',()=>{$('goal').value=goal;void action(saveDraft);$('goal').focus();$('taskForm').scrollIntoView({block:'center',behavior:'instant'})},'example');b.append(node('strong',title+' ↗'));$('examples').append(b)}
const steps=[['连接设备','连接 Android 手机或启动模拟器，打开 USB 调试并授权。'],['创建任务','在首页输入任务目标，或从宿主会话发起。'],['查看结果','在任务详情查看画面、操作记录和截图证据。']];steps.forEach(([title,text],i)=>{const section=node('section',undefined,'guide-step'),body=node('div');body.append(node('h2',title),node('p',text));section.append(node('span',String(i+1).padStart(2,'0'),'number'),body);$('guideSteps').append(section)});
action(async()=>{await refresh();await devices()});setInterval(()=>refresh().catch(e=>$('error').textContent=e.message),1500);setInterval(()=>devices().catch(e=>$('error').textContent=e.message),10000);
`
