import { defineConfig } from 'tsdown'

/** Bundle the plugin and invariant companion while keeping Harness peers external. */
export default defineConfig([
  {
    name: 'opengui/task-service',
    entry: { 'task-service': 'lib/types/deepseek-harness-plugin/src/task-service.js' },
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    deps: { alwaysBundle: id => !id.startsWith('node:') },
    outputOptions: { codeSplitting: false },
    dts: false,
    clean: false,
  },
  { entry: ['lib/types/deepseek-harness-plugin/src/phone-worker.js'], outDir: 'lib', format: ['esm'], platform: 'node', target: 'es2024', fixedExtension: false, dts: false, clean: false, outputOptions: { codeSplitting: false } },
  {
    entry: ['lib/types/deepseek-harness-plugin/src/index.js'],
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    outputOptions: { codeSplitting: false },
    dts: false,
    clean: false,
  },
  {
    entry: ['lib/types/deepseek-harness-plugin/src/invariant.js'],
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    outputOptions: { codeSplitting: false },
    dts: false,
    clean: false,
  },
  {
    name: 'opengui/codex-mcp',
    entry: ['lib/types/deepseek-harness-plugin/src/codex-mcp.js'],
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    deps: { alwaysBundle: id => !id.startsWith('node:') },
    outputOptions: { codeSplitting: false },
    dts: false,
    clean: false,
  },
  {
    name: 'opengui/codex-cli',
    entry: ['lib/types/deepseek-harness-plugin/src/codex-cli.js'],
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    deps: { alwaysBundle: id => !id.startsWith('node:') },
    outputOptions: { codeSplitting: false },
    dts: false,
    clean: false,
  },
  {
    name: 'dsh-coremate-mobile/client',
    entry: { client: 'lib/types/deepseek-harness-plugin/src/client/index.js' },
    outDir: 'lib',
    format: ['cjs'],
    platform: 'browser',
    target: 'es2022',
    deps: {
      neverBundle: [
        'react',
        'react/jsx-runtime',
        '@deepseek-ai/cordis',
        '@deepseek-ai/dsh-client-ui-slots',
      ],
      alwaysBundle: id => ![
        'react',
        'react/jsx-runtime',
        '@deepseek-ai/cordis',
        '@deepseek-ai/dsh-client-ui-slots',
      ].includes(id),
    },
    sourcemap: true,
    dts: false,
    clean: false,
    outputOptions: {
      entryFileNames: 'client.js',
      banner: 'window.__ModuleLoader__.load({ id: "dsh-coremate-mobile", factory: (require) => {',
      footer: 'return module.exports; } });',
      intro: 'var module = { exports: {} }; var exports = module.exports;',
      codeSplitting: false,
    },
  },
])
